name: "Custom Action"
description: "A simple composite action that greets the user and prints the current date"
inputs:
  name:

    description: "The name of the user to greet"
    required: true
runs:
  using: "composite"
  steps:
    - name: Greet the user
      run: echo "Hello, ${{ inputs.name }}!"
      shell: bash

    - name: Print the date
      run: date
      shell: bash
