name: CI

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run My Customn Action
        uses: actions/hello-world-composite-action
        with:
          name: "World"
